---
- name: write the rsyslog config file
  template:
    src: rsyslog.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  notify:
   - restart rsyslog
- name: ensure rsyslog is running
  service:
    name: rsyslog
    state: started
    enabled: yes
